### ISSUE TITLE
Changing START_DATE to 2019 causes 2nd graph to have incorrect X axis (date) labels

### ISSUE THREAD

**Issue by garyo** [williamwissemann/TamperMonkeyScripts#2]
Just FYI, if I change the constant START_DATE to 2019-01-01, it causes the bottom "REPORT FILTERS" graph to have incorrect dates -- they go out to 2032 for me. I know this isn't supported, but just thought you might want to know.

**Comment by williamwissemann** [comment]
To minimize load on the MM servers, the "REPORT FILTERS" graph is being cached in the browser's local storage. If you change the START_DATE you also need to clear the cached data. In dev tools, if you run `localStorage["tm:AccountPageRecentBalance"] = "{}"` and then refresh the page, the dates should be correct.
